# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0003_auto_20161010_0348'),
        ('movie_data', '0002_auto_20161009_1915'),
    ]

    operations = [
    ]
